name: Swift

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.4.app/Contents/Developer'
    - name: Show versions 
      run: |
        xcodebuild -version
        swift -version
        carthage version
    - name: Carthage Update
      run: carthage update --platform iOS --cache-builds
    - name: Xcode Build
      run: xcodebuild -scheme TestApp -sdk iphonesimulator -configuration Debug build
    - name: Show Artifacts
      run: ls -la DerivedData/TestApp/Build/Products/Debug-iphonesimulator/

