on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.4.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Carthage
      run: carthage update --platform iOS --cache-builds
